name: Test ROS Python Wheels on Alpine

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test-alpine-python312:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apk update && apk add --no-cache \
            git \
            bash

      - name: Install ROS Python packages
        run: |
          python3 -m pip install --extra-index-url https://dl.cloudsmith.io/public/ros-python-wheels/jazzy/python/simple/ \
            ros-rclpy[fastrtps] ros-test-msgs pytest

      - name: Set environment variables
        run: |
          echo "RMW_IMPLEMENTATION=rmw_fastrtps_cpp" >> $GITHUB_ENV

      - name: Make test script executable
        run: chmod +x scripts/run_rclpy_tests.sh

      - name: Run RClPy tests
        run: ./scripts/run_rclpy_tests.sh

      - name: Upload test results (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-alpine-python312
          path: |
            /tmp/rclpy_test/
          retention-days: 7
