name: Test ROS Python Wheels Matrix

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.12"
            os-type: alpine
            container: python:3.12-alpine
            install-cmd: apk update && apk add --no-cache git bash
          - python-version: "3.12"
            os-type: ubuntu
            container: python:3.12-slim
            install-cmd: apt-get update && apt-get install -y git

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: ${{ matrix.install-cmd }}

      - name: Install ROS Python packages
        run: |
          python3 -m pip install --extra-index-url https://dl.cloudsmith.io/public/ros-python-wheels/jazzy/python/simple/ \
            ros-rclpy[fastrtps] ros-test-msgs pytest

      - name: Set environment variables
        run: |
          echo "RMW_IMPLEMENTATION=rmw_fastrtps_cpp" >> $GITHUB_ENV

      - name: Make test script executable
        run: chmod +x scripts/run_rclpy_tests.sh

      - name: Run RClPy tests
        run: ./scripts/run_rclpy_tests.sh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os-type }}-python${{ matrix.python-version }}
          path: |
            /tmp/rclpy_test/
          retention-days: 7
